spring:
  application:
    name: SpringBoot-Neo4j
  data:
    neo4j:
      uri: bolt://127.0.0.1:7687
      username: neo4j
      password: 12345

server:
  port: 8084


swagger:
  plus:
    enable: true



forest:
  connect-timeout: 60000      # HTTP请求连接超时时间
  read-timeout: 60000         # HTTP请求读取超时时间
  variables:                  # 自定义变量:
   
    apiKey:XXXXXXXXXXXXXXXXXX  # 你的 OpenAI 的 API KEY
    model: text-davinci-003 # ChartGPT 的模型
    maxTokens: 2000          # 最大 Token 数
    temperature: 0.5          # 该值越大每次返回的结果越随机，即相似度越小


